AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Parameters:
  SNSTopic:
    Type: String    
    MinLength: 3
    Description: (Required) The ARN of the SNS topic to subscribe to and listen to Stripe events from.
    ConstraintDescription: 'Required parameter. Must be characters only.'
  UsersTableName:
    Type: String
    Description: (Required) The name of the DynamoDB table storing users
    MinLength: 3
    ConstraintDescription: 'Required parameter. Must be characters only.'
  PinsTableName:
    Type: String
    Description: (Required) The name of the DynamoDB table storing pins
    MinLength: 3
    ConstraintDescription: 'Required parameter. Must be characters only.'
  MetricsTableName:
    Type: String
    Description: (Required) The name of the DynamoDB table storing metrics
    MinLength: 3
    ConstraintDescription: 'Required parameter. Must be characters only.'
Resources:
  LambdaSubscriber:
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      Handler: lambda.handler
      Runtime: nodejs20.x
      MemorySize: 256
      Timeout: 10
      Description: Subscribes to a SNS topic and listens to Stripe events coming from API Gateway. 
      Architectures:
        - arm64
      Environment:
        Variables:
          TOPIC_ARN: !Ref SNSTopic
          STRIPE_EVENTS_TABLE_NAME: !Ref StripeEventsTable
          USERS_TABLE_NAME: !Ref UsersTableName
          PINS_TABLE_TABLE_NAME: !Ref PinsTableName
          METRICS_TABLE_NAME: !Ref MetricsTableName
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref StripeEventsTable
      Events:
        SubscribedTopic:
          Type: SNS
          Properties:
            Topic: !Ref SNSTopic
  StripeEventsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TimeToLiveSpecification:
        Enabled: true
        AttributeName: ttl
      TableName: StripeEventsTable
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: created
          AttributeType: N
      KeySchema:
        - AttributeName: id
          KeyType: HASH
        - AttributeName: created
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
Outputs:
  DynamoStripeEventsTable:
    Value: !GetAtt StripeEventsTable.Arn
    Description: The ARN of the StripeEventsTable DynamoDB Table
